# Generated by Django 4.0.3 on 2022-06-09 07:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uniid',
            field=models.UUIDField(default=uuid.UUID('f8358c9b-2755-41fd-97db-29268a8aeb09')),
        ),
    ]
