# Generated by Django 4.0.3 on 2022-06-03 06:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0002_delete_prodi'),
    ]

    operations = [
        migrations.CreateModel(
            name='prodi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=90)),
                ('mahasiswa', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
