# Generated by Django 4.0.3 on 2022-06-09 07:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_uniid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uniid',
            field=models.UUIDField(default=uuid.UUID('57ce2f6a-cb63-4916-acbd-eab3c0c6f748'), editable=False),
        ),
    ]
