# Generated by Django 4.0.3 on 2022-06-03 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_prodi'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prodi',
            old_name='mahasiswa',
            new_name='user',
        ),
    ]
