# Generated by Django 4.0.3 on 2022-06-09 07:06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_uniid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uniid',
            field=models.UUIDField(default=uuid.UUID('fb324f58-d028-4704-8f21-b7955aeeb6ef'), editable=False),
        ),
    ]
