# Generated by Django 4.0.3 on 2022-07-04 12:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_user_uniid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uniid',
            field=models.UUIDField(default=uuid.UUID('6623b1b4-bcc2-48dd-84ea-21c2be0e0b56'), editable=False),
        ),
    ]
