# Generated by Django 4.0.3 on 2022-06-03 03:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='prestasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_event', models.CharField(max_length=80)),
                ('url_kegiatan', models.TextField()),
                ('penyelenggara', models.CharField(max_length=80)),
                ('lingkup_tingkat', models.CharField(max_length=50)),
                ('jumlah_negara', models.IntegerField()),
                ('kategori', models.CharField(max_length=50)),
                ('prestasi_diraih', models.CharField(max_length=80)),
                ('ekuivalensi', models.CharField(max_length=80)),
                ('tempat', models.TextField()),
                ('tanggal_mulai', models.DateField()),
                ('tanggal_selesai', models.DateField()),
                ('deskripsi', models.TextField()),
                ('bukti', models.FileField(upload_to='img/')),
                ('foto_kegiatan', models.FileField(upload_to='img/')),
                ('tim_individu', models.CharField(choices=[('tim', 'Tim'), ('individu', 'Individu')], default='individu', max_length=10)),
                ('jenis_prestasi', models.CharField(choices=[('penghargaan', 'penghargaan'), ('seminar', 'seminar'), ('organisasi', 'organisasi')], max_length=20)),
                ('user', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
