# Generated by Django 4.0.3 on 2022-06-10 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestasi_mahasiswa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='mahasiswa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nim', models.CharField(max_length=20)),
                ('prodi', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='prestasi',
            name='mahasiswa',
            field=models.ManyToManyField(to='prestasi_mahasiswa.mahasiswa'),
        ),
    ]
