# Generated by Django 4.0.3 on 2022-06-02 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestasi_mahasiswa', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestasi',
            name='bukti',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='prestasi',
            name='foto_kegiatan',
            field=models.FileField(upload_to=''),
        ),
    ]
