# Generated by Django 4.0.3 on 2022-06-02 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestasi_mahasiswa', '0003_alter_prestasi_bukti_alter_prestasi_foto_kegiatan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestasi',
            name='bukti',
            field=models.FileField(upload_to='img/'),
        ),
        migrations.AlterField(
            model_name='prestasi',
            name='foto_kegiatan',
            field=models.FileField(upload_to='img/'),
        ),
    ]
