# Generated by Django 4.0.2 on 2022-06-02 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestasi_mahasiswa', '0005_alter_prestasi_tanggal_mulai_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestasi',
            name='tanggal_mulai',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='prestasi',
            name='tanggal_selesai',
            field=models.DateField(),
        ),
    ]
